<?php

namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LibrarySeeder extends Seeder
{
    public static array $books = [
        [
            'designation' => 'The Alchemist',
            'designation_ar' => 'الخيميائي',
            'designation_fr' => 'L\'Alchimiste',
            'auteur' => 'Paulo Coelho',
            'description' => 'A magical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure.',
            'description_ar' => 'رواية فلسفية تحكي قصة الراعي الشاب سانتياغو ورحلته للبحث عن كنز مدفون بجانب الأهرامات، تكتشف خلالها قوة الأحلام والإرادة.',
            'description_fr' => 'Le récit d\'un voyage initiatique d\'un jeune berger andalou à la recherche d\'un trésor caché au pied des Pyramides.',
            'prix' => 120.00,
            'cover' => '1.jpg',
            'categorie' => 'Littérature',
            'editeur' => 'HarperOne',
            'annee' => 1988,
            'type' => 'Texte',
            'langue' => 'Multi'
        ],
        [
            'designation' => 'Atomic Habits',
            'designation_ar' => 'عادات ذرية',
            'designation_fr' => 'Des Habitudes Atomiques',
            'auteur' => 'James Clear',
            'description' => 'A proven framework for improving every day. James Clear reveals practical strategies to form good habits and break bad ones.',
            'description_ar' => 'يقدم جيمس كلير دليلاً عملياً لبناء عادات جيدة والتخلص من السيئة، معتمداً على العلم والمنطق لتغيير حياتك تدريجياً.',
            'description_fr' => 'Un guide pratique pour transformer votre vie grâce à de petits changements quotidiens.',
            'prix' => 150.00,
            'cover' => '2.jpg',
            'categorie' => 'Développement Personnel',
            'editeur' => 'Penguin',
            'annee' => 2018,
            'type' => 'Texte',
            'langue' => 'Multi'
        ],
        [
            'designation' => '1984',
            'designation_ar' => '١٩٨٤',
            'designation_fr' => '1984',
            'auteur' => 'George Orwell',
            'description' => 'A dystopian social science fiction novel and cautionary tale about ubiquitous government surveillance and propaganda.',
            'description_ar' => 'تحفة أدبية تحذر من طغيان الأنظمة الاستبدادية، حيث يراقب "الأخ الأكبر" كل شيء حتى أفكار البشر ومشاعرهم.',
            'description_fr' => 'Un classique de la littérature dystopique dépeignant un monde sous surveillance totale.',
            'prix' => 95.00,
            'cover' => '3.jpg',
            'categorie' => 'Littérature',
            'editeur' => 'Secker',
            'annee' => 1949,
            'type' => 'Texte',
            'langue' => 'Multi'
        ],
        [
            'designation' => 'Sapiens',
            'designation_ar' => 'العاقل',
            'designation_fr' => 'Sapiens',
            'auteur' => 'Yuval Noah Harari',
            'description' => 'A brief history of humankind, exploring how biology and history have defined us since the Stone Age.',
            'description_ar' => 'كتاب يحلل تاريخ البشرية من زاوية علمية وفلسفية، وكيف تطور الإنسان ليسود الكوكب بفضل قدرته على التعاون.',
            'description_fr' => 'Une exploration passionnante de l\'histoire de l\'humanité, des grottes à la conquête de l\'espace.',
            'prix' => 165.00,
            'cover' => '4.jpg',
            'categorie' => 'Histoire',
            'editeur' => 'Harvill',
            'annee' => 2011,
            'type' => 'Texte',
            'langue' => 'Multi'
        ],
        [
            'designation' => 'Le Petit Prince',
            'designation_ar' => 'الأمير الصغير',
            'designation_fr' => 'Le Petit Prince',
            'auteur' => 'Antoine de Saint-Exupéry',
            'description' => 'The story of a young prince who visits various planets in space, including Earth, and addresses themes of loneliness and friendship.',
            'description_ar' => 'رواية خيالية فلسفية تذكرنا بأن "الأشياء الجوهرية لا تُرى إلا بالقلب"، وهي من أكثر الكتب ترجمة في العالم.',
            'description_fr' => 'Le conte le plus célèbre de la littérature française, une réflexion poétique sur la vie et l\'amour.',
            'prix' => 70.00,
            'cover' => '5.jpg',
            'categorie' => 'Enfants & Jeunesse',
            'editeur' => 'Gallimard',
            'annee' => 1943,
            'type' => 'Texte',
            'langue' => 'Multi'
        ],
        [
            'designation' => 'Deep Work',
            'designation_ar' => 'العمل العميق',
            'designation_fr' => 'Deep Work',
            'auteur' => 'Cal Newport',
            'description' => 'Rules for focused success in a distracted world, teaching how to master complicated information.',
            'description_ar' => 'دليل عملي للوصول إلى أقصى درجات التركيز في عالم مليء بالمشتتات الرقمية، مما يسمح بإنتاج أعمال عالية الجودة.',
            'description_fr' => 'Retrouver la concentration dans un monde de distractions numériques pour exceller dans son travail.',
            'prix' => 110.00,
            'cover' => '6.jpg',
            'categorie' => 'Développement Personnel',
            'editeur' => 'Grand Central',
            'annee' => 2016,
            'type' => 'Texte',
            'langue' => 'Multi'
        ],
        [
            'designation' => 'The Power of Habit',
            'designation_ar' => 'قوة العادة',
            'designation_fr' => 'Le Pouvoir des Habitudes',
            'auteur' => 'Charles Duhigg',
            'description' => 'A scientific look at why habits exist and how they can be changed to improve our lives and businesses.',
            'description_ar' => 'يستكشف الكتاب الطبيعة العلمية لكيفية عمل العادات وكيف يمكن تغييرها لتحسين الإنتاجية والحياة الشخصية.',
            'description_fr' => 'Une plongée dans la science des habitudes et comment les transformer pour réussir.',
            'prix' => 135.00,
            'cover' => '7.jpg',
            'categorie' => 'Développement Personnel',
            'editeur' => 'Random House',
            'annee' => 2012,
            'type' => 'Texte',
            'langue' => 'Multi'
        ],
        [
            'designation' => 'Thinking, Fast and Slow',
            'designation_ar' => 'التفكير بسرعة وببطء',
            'designation_fr' => 'Système 1 / Système 2',
            'auteur' => 'Daniel Kahneman',
            'description' => 'A renowned psychologist explains the two systems that drive the way we think—System 1 is fast; System 2 is slow.',
            'description_ar' => 'يشرح عالم النفس الحائز على نوبل النظامين اللذين يقودان تفكيرنا، وكيف يؤثر كل منهما على قراراتنا اليومية.',
            'description_fr' => 'Les deux systèmes qui dirigent notre pensée : l\'intuition et la réflexion.',
            'prix' => 170.00,
            'cover' => '8.jpg',
            'categorie' => 'Philosophie',
            'editeur' => 'Farrar',
            'annee' => 2011,
            'type' => 'Texte',
            'langue' => 'Multi'
        ],
        [
            'designation' => 'Rich Dad Poor Dad',
            'designation_ar' => 'الأب الغني والأب الفقير',
            'designation_fr' => 'Père Riche, Père Pauvre',
            'auteur' => 'Robert Kiyosaki',
            'description' => 'An eye-opening guide to financial literacy, personal finance, and investing, contrasting the mindsets of two fathers.',
            'description_ar' => 'كتاب يعلم الثقافة المالية وإدارة الأموال الشخصية والاستثمار، من خلال مقارنة عقلية أب غني وعقلية أب فقير.',
            'description_fr' => 'Un guide indispensable sur la liberté financière et l\'éducation financière des enfants.',
            'prix' => 125.00,
            'cover' => '9.jpg',
            'categorie' => 'Développement Personnel',
            'editeur' => 'Warner Books',
            'annee' => 1997,
            'type' => 'Texte',
            'langue' => 'Multi'
        ],
        [
            'designation' => 'The Subtle Art of Not Giving a F*ck',
            'designation_ar' => 'فن اللامبالاة',
            'designation_fr' => 'L\'art subtil de s\'en ficher',
            'auteur' => 'Mark Manson',
            'description' => 'A self-help guide that advises readers to accept the limits of their abilities and find value in their flaws and challenges.',
            'description_ar' => 'كتاب تنمية بشرية يدعو للتصالح مع الذات وتقبل الصعاب والفشل بدلاً من الجري وراء الإيجابية المزيفة.',
            'description_fr' => 'Un guide d\'auto-assistance pragmatique qui propose de cultiver le détachement face aux futilités.',
            'prix' => 115.00,
            'cover' => '10.jpg',
            'categorie' => 'Développement Personnel',
            'editeur' => 'HarperOne',
            'annee' => 2016,
            'type' => 'Texte',
            'langue' => 'Multi'
        ],
        [
            'designation' => 'Don Quixote',
            'designation_ar' => 'دون كيخوته',
            'designation_fr' => 'Don Quichotte',
            'auteur' => 'Miguel de Cervantes',
            'description' => 'The legendary story of the Spanish noble Alonso Quixano, who loses his mind from reading too many chivalric romances.',
            'description_ar' => 'رواية كلاسيكية شهيرة تروي مغامرات نبل إسباني يفقد عقله بسبب قراءة روايات الفروسية ويبدأ بمحاربة طواحين الهواء.',
            'description_fr' => 'L\'histoire légendaire d\'un noble espagnol qui décide de devenir chevalier errant.',
            'prix' => 105.00,
            'cover' => '11.jpg',
            'categorie' => 'Littérature',
            'editeur' => 'Francisco de Robles',
            'annee' => 1605,
            'type' => 'Texte',
            'langue' => 'Multi'
        ],
        [
            'designation' => 'The Great Gatsby',
            'designation_ar' => 'غاتسبي العظيم',
            'designation_fr' => 'Le Magnifique Gatsby',
            'auteur' => 'F. Scott Fitzgerald',
            'description' => 'A portrait of the Jazz Age, exploring themes of wealth, love, and the disillusionment of the American Dream.',
            'description_ar' => 'رواية تصور عصر الجاز في أمريكا، وتتناول مواضيع الثروة، والحب المستحيل، والوهم المحيط بالحلم الأمريكي.',
            'description_fr' => 'Un chef-d\'œuvre décrivant la haute société américaine des années folles.',
            'prix' => 85.00,
            'cover' => '12.jpg',
            'categorie' => 'Littérature',
            'editeur' => 'Scribner',
            'annee' => 1925,
            'type' => 'Texte',
            'langue' => 'Multi'
        ],
        [
            'designation' => 'Pride and Prejudice',
            'designation_ar' => 'كبرياء وتحامل',
            'designation_fr' => 'Orgueil et Préjugés',
            'auteur' => 'Jane Austen',
            'description' => 'A romantic masterpiece following the turbulent relationship between Elizabeth Bennet and the wealthy Mr. Darcy.',
            'description_ar' => 'قصة حب كلاسيكية تدور حول إليزابيث بينيت والسيد دارسي، وتناقش الفروق الطبقية والكبرياء البشري.',
            'description_fr' => 'Une comédie romantique classique sur les malentendus et les différences sociales.',
            'prix' => 90.00,
            'cover' => '13.jpg',
            'categorie' => 'Littérature',
            'editeur' => 'T. Egerton',
            'annee' => 1813,
            'type' => 'Texte',
            'langue' => 'Multi'
        ],
        [
            'designation' => 'To Kill a Mockingbird',
            'designation_ar' => 'أن تقتل طائراً محاكياً',
            'designation_fr' => 'Ne tirez pas sur l\'oiseau moqueur',
            'auteur' => 'Harper Lee',
            'description' => 'A dramatic novel addressing racism, prejudice, and the loss of innocence in the American South.',
            'description_ar' => 'رواية مؤثرة تناقش العنصرية، والعدالة، وفقدان البراءة في الجنوب الأمريكي من خلال عيون طفلة.',
            'description_fr' => 'Un roman puissant sur le racisme et l\'injustice dans le Sud des États-Unis.',
            'prix' => 110.00,
            'cover' => '14.jpg',
            'categorie' => 'Littérature',
            'editeur' => 'J. B. Lippincott',
            'annee' => 1960,
            'type' => 'Texte',
            'langue' => 'Multi'
        ],
        [
            'designation' => 'Crime and Punishment',
            'designation_ar' => 'الجريمة والعقاب',
            'designation_fr' => 'Crime et Châtiment',
            'auteur' => 'Fyodor Dostoevsky',
            'description' => 'The psychological torment and moral dilemmas of Rodion Raskolnikov, a poor ex-student who plans to kill an unscrupulous pawnbroker.',
            'description_ar' => 'رواية نفسية عميقة تناقش الصراع الأخلاقي والعذاب النفسي لراسكولنيكوف بعد ارتكابه جريمة قتل مبررة في نظره.',
            'description_fr' => 'Le chef-d\'œuvre de Dostoïevski explorant la culpabilité et la rédemption d\'un jeune étudiant.',
            'prix' => 130.00,
            'cover' => '15.jpg',
            'categorie' => 'Littérature',
            'editeur' => 'The Russian Messenger',
            'annee' => 1866,
            'type' => 'Texte',
            'langue' => 'Multi'
        ],
        [
            'designation' => 'Harry Potter and the Philosopher\'s Stone',
            'designation_ar' => 'هاري بوتر وحجر الفيلسوف',
            'designation_fr' => 'Harry Potter à l\'école des sorciers',
            'auteur' => 'J.K. Rowling',
            'description' => 'The start of the legendary wizarding journey of young orphan Harry Potter as he discovers Hogwarts School of Witchcraft and Wizardry.',
            'description_ar' => 'بداية الرحلة الأسطورية للساحر الصغير هاري بوتر بعد اكتشافه قدراته السحرية وانضمامه لمدرسة هوجورتس.',
            'description_fr' => 'Le premier tome des aventures du célèbre sorcier Harry Potter à l\'école de Poudlard.',
            'prix' => 140.00,
            'cover' => '16.jpg',
            'categorie' => 'Enfants & Jeunesse',
            'editeur' => 'Bloomsbury',
            'annee' => 1997,
            'type' => 'Texte',
            'langue' => 'Multi'
        ],
        [
            'designation' => 'The Lord of the Rings',
            'designation_ar' => 'سيد الخواتم',
            'designation_fr' => 'Le Seigneur des Anneaux',
            'auteur' => 'J.R.R. Tolkien',
            'description' => 'An epic high-fantasy masterpiece depicting the quest to destroy the One Ring and defeat the Dark Lord Sauron.',
            'description_ar' => 'ملحمة خيالية كبرى تروي رحلة تدمير الخاتم الأوحد للقضاء على سيد الظلام ساورون وإنقاذ الأرض الوسطى.',
            'description_fr' => 'Une épopée fantastique majeure retraçant la quête pour détruire l\'Anneau Unique.',
            'prix' => 200.00,
            'cover' => '17.jpg',
            'categorie' => 'Littérature',
            'editeur' => 'Allen & Unwin',
            'annee' => 1954,
            'type' => 'Texte',
            'langue' => 'Multi'
        ],
        [
            'designation' => 'Homo Deus',
            'designation_ar' => 'هومو ديوس',
            'designation_fr' => 'Homo Deus',
            'auteur' => 'Yuval Noah Harari',
            'description' => 'An examination of the future of humanity, exploring our dreams, nightmares, and destiny in the 21st century.',
            'description_ar' => 'كتاب يستشرف مستقبل البشرية في القرن الحادي والعشرين، ويرسم ملامح الأحلام والكوابيس التي تنتظر الإنسان.',
            'description_fr' => 'Une réflexion captivante sur l\'avenir de l\'humanité à l\'ère de l\'intelligence artificielle.',
            'prix' => 180.00,
            'cover' => '18.jpg',
            'categorie' => 'Histoire',
            'editeur' => 'Harvill Secker',
            'annee' => 2015,
            'type' => 'Texte',
            'langue' => 'Multi'
        ],
        [
            'designation' => 'The Da Vinci Code',
            'designation_ar' => 'شفرة دا فينشي',
            'designation_fr' => 'Le Code Da Vinci',
            'auteur' => 'Dan Brown',
            'description' => 'A fast-paced mystery thriller following Robert Langdon as he investigates a murder in the Louvre Museum.',
            'description_ar' => 'رواية تشويق وإثارة سريعة الإيقاع يتتبع فيها روبرت لانغدون رموزاً غامضة بعد جريمة قتل في متحف اللوفر.',
            'description_fr' => 'Un thriller ésotérique haletant à la recherche du secret le plus mystérieux de l\'histoire.',
            'prix' => 110.00,
            'cover' => '19.jpg',
            'categorie' => 'Littérature',
            'editeur' => 'Doubleday',
            'annee' => 2003,
            'type' => 'Texte',
            'langue' => 'Multi'
        ],
        [
            'designation' => 'Zero to One',
            'designation_ar' => 'من الصفر إلى الواحد',
            'designation_fr' => 'De zéro à un',
            'auteur' => 'Peter Thiel',
            'description' => 'Notes on startups, and how to build the future. Peter Thiel shows how we can find singular ways to create those new things.',
            'description_ar' => 'يقدم بيتر ثيل رؤية ملهمة لبناء المستقبل وتأسيس شركات ناشئة تبتكر وتخلق أشياء جديدة تماماً.',
            'description_fr' => 'Comment construire le futur grâce aux startups et créer de la valeur à partir de rien.',
            'prix' => 145.00,
            'cover' => '20.jpg',
            'categorie' => 'Économie',
            'editeur' => 'Crown Business',
            'annee' => 2014,
            'type' => 'Texte',
            'langue' => 'Multi'
        ]
    ];

    public function run(): void
    {
        // Delete instead of truncate to avoid foreign key issues
        DB::table('books')->delete();

        foreach (self::$books as $book) {
            Book::create($book);
        }
    }
}
